#!/bin/bash
#
# Simple wrapper for "redis-server" executable.
#
# Usage:  start  [config-filename]
#
# Arguments:
#   - config-filename: default="redis.conf"
#

CONF=${1:-redis.conf}

exec  redis-server  /etc/redis/$CONF
